#!/usr/bin/env python3
# Copyright (c) 2026 The Zcash developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://www.opensource.org/licenses/mit-license.php .

#
# Test that `zallet migrate-zcashd-wallet --no-scan` correctly imports
# keys from a zcashd wallet.dat into zallet.
#
# The test wallet in test-wallet/ was generated by the regtest wallet
# builder [1] and spans all 9 network upgrades (Sprout through NU6.1)
# with HD-derived transparent/sapling/orchard keys, unified accounts,
# and per-phase imported foreign keys (spending keys, viewing keys,
# watch-only addresses).
#
# After import, verifies that all expected addresses appear in
# zallet's listaddresses output. Key material comparison (via
# dumpprivkey, z_exportkey, z_exportviewingkey) is not yet possible
# because zallet does not implement those RPCs.
#
# Sprout keys are intentionally excluded - not supported by zallet.
# Watch-only-by-hash transparent addresses (zcashd `importaddress`) are
# recorded as SKIPPED for the same reason: zallet has no plans to
# support importing watch-only addresses by script-hash alone.
#
# [1] https://github.com/zcash/zcash/tree/master/qa/zcash/wallet-builder
#

import os

from test_framework.test_framework import BitcoinTestFramework
from test_framework.util import (
    assert_true,
    indexer_rpc_port,
    node_dir,
    start_wallet,
    update_zallet_conf,
    wallet_dir,
    wallet_rpc_port,
    rpc_port,
    zallet_binary,
)
from test_framework.zcashd_migration import (
    CheckReporter,
    ImportedKeyKind,
    extract_listed_addresses,
    load_manifest,
    load_phase_manifests,
    run_migration,
    test_wallet_path,
)


class ZcashdKeyImportTest(BitcoinTestFramework):
    def __init__(self):
        super().__init__()
        self.num_nodes = 1
        self.num_wallets = 0   # We set up the wallet manually via migration
        self.num_indexers = 0
        self.cache_behavior = 'clean'

    def prepare_chain(self):
        self.nodes[0].generate(1)

    def run_test(self):
        self.wallets = []

        # Locate test wallet
        test_data = test_wallet_path()
        wallet_dat_path = os.path.join(test_data, 'wallet.dat')
        assert_true(os.path.exists(wallet_dat_path),
            "Test wallet not found at %s" % wallet_dat_path)

        print("Loading manifest from %s" % test_data)
        manifest = load_manifest(test_data)
        phase_manifests = load_phase_manifests(test_data)

        # Set up zallet datadir with config
        zallet = zallet_binary()
        datadir = wallet_dir(self.options.tmpdir, 0)
        # The zebra backend needs the co-located zebrad's indexer port and
        # state directory; the zaino backend ignores both.
        update_zallet_conf(datadir, rpc_port(0), wallet_rpc_port(0),
                           indexer_port=indexer_rpc_port(0),
                           zebra_state_dir=node_dir(self.options.tmpdir, 0))

        run_migration(zallet, datadir, wallet_dat_path)

        print("Starting wallet...")
        wallet = start_wallet(0, self.options.tmpdir)
        self.wallets = [wallet]

        reporter = CheckReporter()

        all_listed = extract_listed_addresses(wallet)
        print("listaddresses contains: %d addresses" % len(all_listed))

        print("Verifying HD transparent addresses...")
        for addr in manifest['all_addresses']['transparent']:
            reporter.check("listaddresses HD transparent: %s" % addr,
                addr in all_listed,
                "present" if addr in all_listed else "MISSING")

        print("Verifying HD sapling addresses...")
        for addr in manifest['all_addresses']['sapling']:
            reporter.check("listaddresses HD sapling: %s" % addr,
                addr in all_listed,
                "present" if addr in all_listed else "MISSING")

        print("Verifying HD orchard/unified addresses...")
        for ua_addr in manifest['all_addresses']['orchard']:
            short = "%s...%s" % (ua_addr[:20], ua_addr[-8:])
            reporter.check("listaddresses HD orchard: %s" % short,
                ua_addr in all_listed,
                "present" if ua_addr in all_listed else "MISSING")

        print("Verifying imported keys per phase...")
        for pm in phase_manifests:
            phase = pm['phase']
            imported = pm.get('imported_keys', {})
            if not imported:
                continue

            for kind in (ImportedKeyKind.TRANSPARENT_PRIVKEY,
                         ImportedKeyKind.TRANSPARENT_WATCHONLY,
                         ImportedKeyKind.TRANSPARENT_P2SH,
                         ImportedKeyKind.TRANSPARENT_PUBKEY,
                         ImportedKeyKind.SAPLING_SPENDING,
                         ImportedKeyKind.SAPLING_VIEWING):
                if kind not in imported:
                    continue
                addr = imported[kind]['address']
                if kind == ImportedKeyKind.TRANSPARENT_WATCHONLY:
                    reporter.skip("listaddresses phase %d %s: %s" % (
                             phase, kind.replace('_', ' '), addr),
                         "SKIPPED - watch-only-by-hash not supported by zallet")
                    continue
                reporter.check("listaddresses phase %d %s: %s" % (
                          phase, kind.replace('_', ' '), addr),
                      addr in all_listed,
                      "present" if addr in all_listed else "MISSING")

            # Sprout keys intentionally skipped - not supported by zallet.

        reporter.finish()


if __name__ == '__main__':
    ZcashdKeyImportTest().main()
