# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: compact_formats.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'compact_formats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63ompact_formats.proto\x12\x15\x63\x61sh.z.wallet.sdk.rpc\"U\n\rChainMetadata\x12!\n\x19saplingCommitmentTreeSize\x18\x01 \x01(\r\x12!\n\x19orchardCommitmentTreeSize\x18\x02 \x01(\r\"\xde\x01\n\x0c\x43ompactBlock\x12\x14\n\x0cprotoVersion\x18\x01 \x01(\r\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\x12\x10\n\x08prevHash\x18\x04 \x01(\x0c\x12\x0c\n\x04time\x18\x05 \x01(\r\x12\x0e\n\x06header\x18\x06 \x01(\x0c\x12-\n\x03vtx\x18\x07 \x03(\x0b\x32 .cash.z.wallet.sdk.rpc.CompactTx\x12;\n\rchainMetadata\x18\x08 \x01(\x0b\x32$.cash.z.wallet.sdk.rpc.ChainMetadata\"\xca\x02\n\tCompactTx\x12\r\n\x05index\x18\x01 \x01(\x04\x12\x0c\n\x04txid\x18\x02 \x01(\x0c\x12\x0b\n\x03\x66\x65\x65\x18\x03 \x01(\r\x12:\n\x06spends\x18\x04 \x03(\x0b\x32*.cash.z.wallet.sdk.rpc.CompactSaplingSpend\x12<\n\x07outputs\x18\x05 \x03(\x0b\x32+.cash.z.wallet.sdk.rpc.CompactSaplingOutput\x12<\n\x07\x61\x63tions\x18\x06 \x03(\x0b\x32+.cash.z.wallet.sdk.rpc.CompactOrchardAction\x12/\n\x03vin\x18\x07 \x03(\x0b\x32\".cash.z.wallet.sdk.rpc.CompactTxIn\x12*\n\x04vout\x18\x08 \x03(\x0b\x32\x1c.cash.z.wallet.sdk.rpc.TxOut\"8\n\x0b\x43ompactTxIn\x12\x13\n\x0bprevoutTxid\x18\x01 \x01(\x0c\x12\x14\n\x0cprevoutIndex\x18\x02 \x01(\r\",\n\x05TxOut\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x14\n\x0cscriptPubKey\x18\x02 \x01(\x0c\"!\n\x13\x43ompactSaplingSpend\x12\n\n\x02nf\x18\x01 \x01(\x0c\"M\n\x14\x43ompactSaplingOutput\x12\x0b\n\x03\x63mu\x18\x01 \x01(\x0c\x12\x14\n\x0c\x65phemeralKey\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\"`\n\x14\x43ompactOrchardAction\x12\x11\n\tnullifier\x18\x01 \x01(\x0c\x12\x0b\n\x03\x63mx\x18\x02 \x01(\x0c\x12\x14\n\x0c\x65phemeralKey\x18\x03 \x01(\x0c\x12\x12\n\nciphertext\x18\x04 \x01(\x0c\x42\x1bZ\x16lightwalletd/walletrpc\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'compact_formats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\026lightwalletd/walletrpc\272\002\000'
  _globals['_CHAINMETADATA']._serialized_start=48
  _globals['_CHAINMETADATA']._serialized_end=133
  _globals['_COMPACTBLOCK']._serialized_start=136
  _globals['_COMPACTBLOCK']._serialized_end=358
  _globals['_COMPACTTX']._serialized_start=361
  _globals['_COMPACTTX']._serialized_end=691
  _globals['_COMPACTTXIN']._serialized_start=693
  _globals['_COMPACTTXIN']._serialized_end=749
  _globals['_TXOUT']._serialized_start=751
  _globals['_TXOUT']._serialized_end=795
  _globals['_COMPACTSAPLINGSPEND']._serialized_start=797
  _globals['_COMPACTSAPLINGSPEND']._serialized_end=830
  _globals['_COMPACTSAPLINGOUTPUT']._serialized_start=832
  _globals['_COMPACTSAPLINGOUTPUT']._serialized_end=909
  _globals['_COMPACTORCHARDACTION']._serialized_start=911
  _globals['_COMPACTORCHARDACTION']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
