# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import compact_formats_pb2 as compact__formats__pb2
from . import service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CompactTxStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLatestBlock = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock',
                request_serializer=service__pb2.ChainSpec.SerializeToString,
                response_deserializer=service__pb2.BlockID.FromString,
                _registered_method=True)
        self.GetBlock = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock',
                request_serializer=service__pb2.BlockID.SerializeToString,
                response_deserializer=compact__formats__pb2.CompactBlock.FromString,
                _registered_method=True)
        self.GetBlockNullifiers = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockNullifiers',
                request_serializer=service__pb2.BlockID.SerializeToString,
                response_deserializer=compact__formats__pb2.CompactBlock.FromString,
                _registered_method=True)
        self.GetBlockRange = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange',
                request_serializer=service__pb2.BlockRange.SerializeToString,
                response_deserializer=compact__formats__pb2.CompactBlock.FromString,
                _registered_method=True)
        self.GetBlockRangeNullifiers = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRangeNullifiers',
                request_serializer=service__pb2.BlockRange.SerializeToString,
                response_deserializer=compact__formats__pb2.CompactBlock.FromString,
                _registered_method=True)
        self.GetTransaction = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction',
                request_serializer=service__pb2.TxFilter.SerializeToString,
                response_deserializer=service__pb2.RawTransaction.FromString,
                _registered_method=True)
        self.SendTransaction = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/SendTransaction',
                request_serializer=service__pb2.RawTransaction.SerializeToString,
                response_deserializer=service__pb2.SendResponse.FromString,
                _registered_method=True)
        self.GetTaddressTxids = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressTxids',
                request_serializer=service__pb2.TransparentAddressBlockFilter.SerializeToString,
                response_deserializer=service__pb2.RawTransaction.FromString,
                _registered_method=True)
        self.GetTaddressTransactions = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressTransactions',
                request_serializer=service__pb2.TransparentAddressBlockFilter.SerializeToString,
                response_deserializer=service__pb2.RawTransaction.FromString,
                _registered_method=True)
        self.GetTaddressBalance = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalance',
                request_serializer=service__pb2.AddressList.SerializeToString,
                response_deserializer=service__pb2.Balance.FromString,
                _registered_method=True)
        self.GetTaddressBalanceStream = channel.stream_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalanceStream',
                request_serializer=service__pb2.Address.SerializeToString,
                response_deserializer=service__pb2.Balance.FromString,
                _registered_method=True)
        self.GetMempoolTx = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolTx',
                request_serializer=service__pb2.GetMempoolTxRequest.SerializeToString,
                response_deserializer=compact__formats__pb2.CompactTx.FromString,
                _registered_method=True)
        self.GetMempoolStream = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolStream',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.RawTransaction.FromString,
                _registered_method=True)
        self.GetTreeState = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTreeState',
                request_serializer=service__pb2.BlockID.SerializeToString,
                response_deserializer=service__pb2.TreeState.FromString,
                _registered_method=True)
        self.GetLatestTreeState = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestTreeState',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.TreeState.FromString,
                _registered_method=True)
        self.GetSubtreeRoots = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetSubtreeRoots',
                request_serializer=service__pb2.GetSubtreeRootsArg.SerializeToString,
                response_deserializer=service__pb2.SubtreeRoot.FromString,
                _registered_method=True)
        self.GetAddressUtxos = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxos',
                request_serializer=service__pb2.GetAddressUtxosArg.SerializeToString,
                response_deserializer=service__pb2.GetAddressUtxosReplyList.FromString,
                _registered_method=True)
        self.GetAddressUtxosStream = channel.unary_stream(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxosStream',
                request_serializer=service__pb2.GetAddressUtxosArg.SerializeToString,
                response_deserializer=service__pb2.GetAddressUtxosReply.FromString,
                _registered_method=True)
        self.GetLightdInfo = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.LightdInfo.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/cash.z.wallet.sdk.rpc.CompactTxStreamer/Ping',
                request_serializer=service__pb2.Duration.SerializeToString,
                response_deserializer=service__pb2.PingResponse.FromString,
                _registered_method=True)


class CompactTxStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLatestBlock(self, request, context):
        """Return the BlockID of the block at the tip of the best chain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlock(self, request, context):
        """Return the compact block corresponding to the given block identifier
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockNullifiers(self, request, context):
        """Same as GetBlock except the returned CompactBlock value contains only
        nullifiers.

        Note: this method is deprecated. Implementations should ignore any
        `PoolType::TRANSPARENT` member of the `poolTypes` argument.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockRange(self, request, context):
        """Return a list of consecutive compact blocks in the specified range,
        which is inclusive of `range.end`.

        If range.start <= range.end, blocks are returned increasing height order;
        otherwise blocks are returned in decreasing height order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBlockRangeNullifiers(self, request, context):
        """Same as GetBlockRange except the returned CompactBlock values contain
        only nullifiers.

        Note: this method is deprecated. Implementations should ignore any
        `PoolType::TRANSPARENT` member of the `poolTypes` argument.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransaction(self, request, context):
        """Return the requested full (not compact) transaction (as from zcashd)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTransaction(self, request, context):
        """Submit the given transaction to the Zcash network
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaddressTxids(self, request, context):
        """Return RawTransactions that match the given transparent address filter.

        Note: This function is misnamed, it returns complete `RawTransaction` values, not TxIds.
        NOTE: this method is deprecated, please use GetTaddressTransactions instead.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaddressTransactions(self, request, context):
        """Return the transactions corresponding to the given t-address within the given block range.
        Mempool transactions are not included in the results.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaddressBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaddressBalanceStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMempoolTx(self, request, context):
        """Returns a stream of the compact transaction representation for transactions
        currently in the mempool. The results of this operation may be a few
        seconds out of date. If the `exclude_txid_suffixes` list is empty,
        return all transactions; otherwise return all *except* those in the
        `exclude_txid_suffixes` list (if any); this allows the client to avoid
        receiving transactions that it already has (from an earlier call to this
        RPC). The transaction IDs in the `exclude_txid_suffixes` list can be
        shortened to any number of bytes to make the request more
        bandwidth-efficient; if two or more transactions in the mempool match a
        txid suffix, none of the matching transactions are excluded. Txid
        suffixes in the exclude list that don't match any transactions in the
        mempool are ignored.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMempoolStream(self, request, context):
        """Return a stream of current Mempool transactions. This will keep the output stream open while
        there are mempool transactions. It will close the returned stream when a new block is mined.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTreeState(self, request, context):
        """GetTreeState returns the note commitment tree state corresponding to the given block.
        See section 3.7 of the Zcash protocol specification. It returns several other useful
        values also (even though they can be obtained using GetBlock).
        The block can be specified by either height or hash.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestTreeState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSubtreeRoots(self, request, context):
        """Returns a stream of information about roots of subtrees of the note commitment tree
        for the specified shielded protocol (Sapling or Orchard).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddressUtxos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAddressUtxosStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLightdInfo(self, request, context):
        """Return information about this lightwalletd instance and the blockchain
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Testing-only, requires lightwalletd --ping-very-insecure (do not enable in production)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CompactTxStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLatestBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestBlock,
                    request_deserializer=service__pb2.ChainSpec.FromString,
                    response_serializer=service__pb2.BlockID.SerializeToString,
            ),
            'GetBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlock,
                    request_deserializer=service__pb2.BlockID.FromString,
                    response_serializer=compact__formats__pb2.CompactBlock.SerializeToString,
            ),
            'GetBlockNullifiers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBlockNullifiers,
                    request_deserializer=service__pb2.BlockID.FromString,
                    response_serializer=compact__formats__pb2.CompactBlock.SerializeToString,
            ),
            'GetBlockRange': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlockRange,
                    request_deserializer=service__pb2.BlockRange.FromString,
                    response_serializer=compact__formats__pb2.CompactBlock.SerializeToString,
            ),
            'GetBlockRangeNullifiers': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBlockRangeNullifiers,
                    request_deserializer=service__pb2.BlockRange.FromString,
                    response_serializer=compact__formats__pb2.CompactBlock.SerializeToString,
            ),
            'GetTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTransaction,
                    request_deserializer=service__pb2.TxFilter.FromString,
                    response_serializer=service__pb2.RawTransaction.SerializeToString,
            ),
            'SendTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTransaction,
                    request_deserializer=service__pb2.RawTransaction.FromString,
                    response_serializer=service__pb2.SendResponse.SerializeToString,
            ),
            'GetTaddressTxids': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTaddressTxids,
                    request_deserializer=service__pb2.TransparentAddressBlockFilter.FromString,
                    response_serializer=service__pb2.RawTransaction.SerializeToString,
            ),
            'GetTaddressTransactions': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTaddressTransactions,
                    request_deserializer=service__pb2.TransparentAddressBlockFilter.FromString,
                    response_serializer=service__pb2.RawTransaction.SerializeToString,
            ),
            'GetTaddressBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaddressBalance,
                    request_deserializer=service__pb2.AddressList.FromString,
                    response_serializer=service__pb2.Balance.SerializeToString,
            ),
            'GetTaddressBalanceStream': grpc.stream_unary_rpc_method_handler(
                    servicer.GetTaddressBalanceStream,
                    request_deserializer=service__pb2.Address.FromString,
                    response_serializer=service__pb2.Balance.SerializeToString,
            ),
            'GetMempoolTx': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMempoolTx,
                    request_deserializer=service__pb2.GetMempoolTxRequest.FromString,
                    response_serializer=compact__formats__pb2.CompactTx.SerializeToString,
            ),
            'GetMempoolStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMempoolStream,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.RawTransaction.SerializeToString,
            ),
            'GetTreeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTreeState,
                    request_deserializer=service__pb2.BlockID.FromString,
                    response_serializer=service__pb2.TreeState.SerializeToString,
            ),
            'GetLatestTreeState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestTreeState,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.TreeState.SerializeToString,
            ),
            'GetSubtreeRoots': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSubtreeRoots,
                    request_deserializer=service__pb2.GetSubtreeRootsArg.FromString,
                    response_serializer=service__pb2.SubtreeRoot.SerializeToString,
            ),
            'GetAddressUtxos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAddressUtxos,
                    request_deserializer=service__pb2.GetAddressUtxosArg.FromString,
                    response_serializer=service__pb2.GetAddressUtxosReplyList.SerializeToString,
            ),
            'GetAddressUtxosStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetAddressUtxosStream,
                    request_deserializer=service__pb2.GetAddressUtxosArg.FromString,
                    response_serializer=service__pb2.GetAddressUtxosReply.SerializeToString,
            ),
            'GetLightdInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightdInfo,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.LightdInfo.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=service__pb2.Duration.FromString,
                    response_serializer=service__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cash.z.wallet.sdk.rpc.CompactTxStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cash.z.wallet.sdk.rpc.CompactTxStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CompactTxStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLatestBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestBlock',
            service__pb2.ChainSpec.SerializeToString,
            service__pb2.BlockID.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlock',
            service__pb2.BlockID.SerializeToString,
            compact__formats__pb2.CompactBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockNullifiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockNullifiers',
            service__pb2.BlockID.SerializeToString,
            compact__formats__pb2.CompactBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockRange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRange',
            service__pb2.BlockRange.SerializeToString,
            compact__formats__pb2.CompactBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBlockRangeNullifiers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetBlockRangeNullifiers',
            service__pb2.BlockRange.SerializeToString,
            compact__formats__pb2.CompactBlock.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTransaction',
            service__pb2.TxFilter.SerializeToString,
            service__pb2.RawTransaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/SendTransaction',
            service__pb2.RawTransaction.SerializeToString,
            service__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaddressTxids(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressTxids',
            service__pb2.TransparentAddressBlockFilter.SerializeToString,
            service__pb2.RawTransaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaddressTransactions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressTransactions',
            service__pb2.TransparentAddressBlockFilter.SerializeToString,
            service__pb2.RawTransaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaddressBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalance',
            service__pb2.AddressList.SerializeToString,
            service__pb2.Balance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaddressBalanceStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTaddressBalanceStream',
            service__pb2.Address.SerializeToString,
            service__pb2.Balance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMempoolTx(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolTx',
            service__pb2.GetMempoolTxRequest.SerializeToString,
            compact__formats__pb2.CompactTx.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMempoolStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetMempoolStream',
            service__pb2.Empty.SerializeToString,
            service__pb2.RawTransaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTreeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetTreeState',
            service__pb2.BlockID.SerializeToString,
            service__pb2.TreeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestTreeState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLatestTreeState',
            service__pb2.Empty.SerializeToString,
            service__pb2.TreeState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSubtreeRoots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetSubtreeRoots',
            service__pb2.GetSubtreeRootsArg.SerializeToString,
            service__pb2.SubtreeRoot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddressUtxos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxos',
            service__pb2.GetAddressUtxosArg.SerializeToString,
            service__pb2.GetAddressUtxosReplyList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAddressUtxosStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetAddressUtxosStream',
            service__pb2.GetAddressUtxosArg.SerializeToString,
            service__pb2.GetAddressUtxosReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLightdInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/GetLightdInfo',
            service__pb2.Empty.SerializeToString,
            service__pb2.LightdInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cash.z.wallet.sdk.rpc.CompactTxStreamer/Ping',
            service__pb2.Duration.SerializeToString,
            service__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
